name: Create Hotfix or Feature Branch on Issue Opened

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create branch from main based on label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name.toLowerCase());
            const isHotfix = labels.includes('hotfix');

            const branchType = isHotfix ? 'hotfix' : 'feature';
            const issueNumber = issue.number;
            const branchName = `${branchType}/issue-${issueNumber}`;

            console.log(`Creating branch: ${branchName}`);

            const { data: mainRef } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/main'
            });

            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`
              });
              console.log(`Branch ${branchName} already exists, skipping creation.`);
            } catch (error) {
              if (error.status === 404) {
                await github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `refs/heads/${branchName}`,
                  sha: mainRef.object.sha
                });
                console.log(`Branch ${branchName} created successfully.`);
              } else {
                throw error;
              }
            }