name: Post CI/CD Instructions on PR

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  comment-guide:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Post CI/CD trigger guide
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const sourceBranch = pr.head.ref;
            const isHotfix = sourceBranch.startsWith("hotfix/");

            const standardBody = `👋 To complete the CI/CD pipeline, please comment the following commands in sequence:
            
            * [ ] merge & build and deploy for development
            * [ ] merge & build for staging
            * [ ] deploy for staging
            * [ ] deploy for production
            
            Each comment will trigger a corresponding GitHub Actions workflow.
            
            ✅ All steps must be completed **before merging** into main.
            
            Good luck! 🚀
            `;
            
            const hotfixBody = `🚑 This is a **hotfix** branch PR — fast-tracking to production!
            
            Closing this pull request after a successful merge will trigger the production deployment workflow.
            
            Thanks for patching things up! 🔧
            `;
            
            const commentBody = isHotfix ? hotfixBody : standardBody;

            await github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody.trim()
            });
